import asyncio,sys,json
from playwright.async_api import async_playwright
BASE=sys.argv[1] if len(sys.argv)>1 else 'file:///workspace/notorious-weasel/index.html'
OUT='/workspace/notorious-weasel/'
LIVE=len(sys.argv)>1
ok=True
def chk(n,c,info=''):
    global ok;ok&=bool(c);print(('PASS ' if c else 'FAIL ')+n,info)
async def run(p,b,name,dev,touch,shots):
    errs=[]
    ctx=await b.new_context(**dev,permissions=['clipboard-read','clipboard-write'])
    m=await ctx.new_page()
    m.on('console',lambda x: errs.append(f'{x.type}: {x.text}') if x.type in('error','warning') else None)
    m.on('pageerror',lambda e: errs.append(f'pageerror {e}'))
    await m.goto(BASE);await m.wait_for_timeout(700)
    chk(f'[{name}] public build has no __NW',await m.evaluate('typeof window.__NW')=='undefined')
    await m.goto(BASE+'?debug=1');await m.wait_for_timeout(900)
    tap=(lambda x,y: m.touchscreen.tap(x,y)) if touch else (lambda x,y: m.mouse.click(x,y))
    r=await m.evaluate('(()=>{const r=document.getElementById("c").getBoundingClientRect();return[r.x,r.y,r.width,r.height]})()')
    vp=await m.evaluate('[innerWidth,innerHeight]')
    chk(f'[{name}] canvas fits viewport',r[0]>=0 and r[1]>=0 and r[0]+r[2]<=vp[0]+1 and r[1]+r[3]<=vp[1]+1,f'{r} vp {vp}')
    cx,cy=r[0]+r[2]/2,r[1]+r[3]*0.5
    await tap(cx,cy);await m.wait_for_timeout(1500)
    a=await m.evaluate('({u:__NW.audio.unlocked,run:__NW.audio.running,clips:__NW.audio.clipCount,st:__NW.state,theme:__NW.audio.theme})')
    chk(f'[{name}] first tap unlocks audio, stays on title',a['u'] and a['run'] and a['st']=='title',str(a))
    chk(f'[{name}] voice clips decoded',a['clips']>=85,str(a['clips']))
    chk(f'[{name}] title boom-bap theme',a['theme']=='title',a['theme'])
    if shots: await m.screenshot(path=OUT+'screenshot-title.png')
    await tap(cx,cy);await m.wait_for_function('__NW.state==="play"',timeout=5000)
    await m.wait_for_timeout(2600)
    e=await m.evaluate('__NW.enemies()');chk(f'[{name}] track 1 formation spawned',len(e)>=8,str(len(e)))
    chk(f'[{name}] auto-fire footballs',await m.evaluate('__NW.balls')>0)
    # drag to move (relative)
    p0=await m.evaluate('__NW.player');c0=await m.evaluate(f'__NW.clientOf({p0["x"]},{p0["y"]+40})')
    if touch:
        cdp=await ctx.new_cdp_session(m)
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':c0['x'],'y':c0['y']}]})
        for i in range(1,11): await cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':c0['x']-i*9,'y':c0['y']}]});await m.wait_for_timeout(16)
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
    else:
        await m.mouse.move(c0['x'],c0['y']);await m.mouse.down()
        for i in range(1,11): await m.mouse.move(c0['x']-i*9,c0['y']);await m.wait_for_timeout(16)
        await m.mouse.up()
    p1=await m.evaluate('__NW.player');chk(f'[{name}] drag moves weasel left',p1['x']<p0['x']-40,f"{p0['x']:.0f}->{p1['x']:.0f}")
    if shots:
        await m.evaluate('__NW.clearAll();__NW.lives=9;__NW.track(2)');await m.wait_for_timeout(3300)
        await m.evaluate('__NW.lives=3')
        await m.evaluate('__NW.star("rapid",__NW.player.x+50,__NW.player.y-150);__NW.lives=3');await m.wait_for_timeout(300)
        await m.screenshot(path=OUT+'screenshot-gameplay.png')
    # controlled scene
    await m.evaluate('__NW.clearAll();__NW.hold();__NW.movePlayer(180,600)')
    s0=await m.evaluate('__NW.score')
    await m.evaluate('__NW.spawn("caleb",180,420);__NW.freezeEnemies()');await m.wait_for_timeout(1500)
    s=await m.evaluate('({s:__NW.score,p:__NW.problems,pc:__NW.potCount,tp:__NW.tp,st:__NW.audio.stats()})')
    chk(f'[{name}] football kills Caleb -> porta-potty + TP confetti',s['pc']==1 and s['s']>s0 and s['p']>=1,str({k:s[k] for k in ['s','p','pc','tp']}))
    chk(f'[{name}] porta-potty sting voiced',s['st'].get('a_potty',0)+s['st'].get('clip',0)>=1,json.dumps(s['st']))
    # star catch (shoot passes through)
    await m.evaluate('__NW.star("spread",__NW.player.x,__NW.player.y-30)');await m.wait_for_timeout(900)
    pl=await m.evaluate('__NW.player');chk(f'[{name}] caught gold Brett star -> triple threat',pl['spreadT']>0,str(pl))
    # enemy INT hurts
    lv=await m.evaluate('__NW.lives');await m.evaluate('__NW.shot("int",__NW.player.x,__NW.player.y-40)');await m.wait_for_timeout(500)
    chk(f'[{name}] Darnold INT costs a life',await m.evaluate('__NW.lives')==lv-1)
    # SHIT COMBO finisher
    await m.wait_for_timeout(2300)
    for i,k in enumerate(['mhj','pitts','darnold','trade','pick4','year4']): await m.evaluate(f'__NW.spawn("{k}",{40+i*56},{140+(i%2)*50})')
    await m.evaluate('__NW.freezeEnemies();__NW.balloonGo(260)');await m.wait_for_timeout(500)
    if shots: await m.screenshot(path=OUT+'screenshot-balloon.png')
    await m.evaluate('__NW.meter=99.5;__NW.spawn("pick4",180,400);__NW.freezeEnemies()');await m.wait_for_timeout(700)
    f=await m.evaluate('({n:__NW.firesales,e:__NW.enemies().length,b:__NW.balloon})')
    chk(f'[{name}] full SHIT COMBO -> FIRE SALE clears screen',f['n']==1 and f['e']==0 and f['b'] is None,str(f))
    await m.wait_for_timeout(1500)
    # boss
    await m.evaluate('__NW.lives=99;__NW.bossGo()');rain=0
    for i in range(14):
        await m.wait_for_timeout(300);rain=max(rain,await m.evaluate('__NW.rain'))
        if shots and i==9: await m.screenshot(path=OUT+'screenshot-boss.png')
    bh=await m.evaluate('__NW.boss');chk(f'[{name}] Weasel Dynasty boss takes football hits',bh and bh['hp']<bh['max'],str(bh))
    chk(f'[{name}] boss rains Mahomes/Lamb/Lamar/CMC cards',rain>=1,str(rain))
    await m.evaluate('__NW.setBossHp(Math.round(__NW.boss.max*0.6))');await m.wait_for_timeout(500)
    f=await m.evaluate('({ph:__NW.bossPhase,ta:__NW.bossTaunt,fm:__NW.finMode,ft:__NW.finT})')
    chk(f'[{name}] boss phase -> weasel EAT SHIT slow-mo taunt (invulnerable)',f['ph']==1 and f['ta']>0 and f['fm']=='weasel' and f['ft']>0,str(f))
    if shots: await m.screenshot(path=OUT+'screenshot-eatshit.png')
    await m.wait_for_timeout(2600)
    await m.evaluate('__NW.lives=99;__NW.setBossHp(1)');await m.wait_for_timeout(5200)
    bh=await m.evaluate('__NW.boss');chk(f'[{name}] boss beatable (Joe wins one, Weasel still champ)',bh is None or bh['dead']==1,str(bh))
    await m.wait_for_timeout(3800)
    chk(f'[{name}] remix loop starts after boss',await m.evaluate('__NW.loop')==1 and await m.evaluate('__NW.trackI')==0)
    z=await m.evaluate('({sy:scrollY,sc:visualViewport.scale,ta:getComputedStyle(document.body).touchAction})')
    chk(f'[{name}] no scroll/zoom',z['sy']==0 and z['sc']==1 and z['ta']=='none',str(z))
    st=await m.evaluate('__NW.audio.stats()');chk(f'[{name}] voice clips played',st.get('clip',0)+st.get('sting',0)>=4,json.dumps(st))
    await m.evaluate('__NW.lives=1;__NW.noInv();__NW.shot("int",__NW.player.x,__NW.player.y-30)');await m.wait_for_timeout(600)
    f=await m.evaluate('({fm:__NW.finMode,ft:__NW.finT,st:__NW.state,l:__NW.lives})')
    chk(f'[{name}] game over -> weasel EAT SHIT taunt',f['fm']=='weasel' and f['ft']>0 and f['l']==0,str(f))
    await m.wait_for_timeout(3600)
    chk(f'[{name}] end screen + initials prompt',await m.evaluate('__NW.state')=='end' and await m.evaluate('__NW.hsEntering'))
    await m.fill('#hsIn','bmw');await m.click('#hsOk');await m.wait_for_timeout(1400)
    lb=await m.evaluate('__NW.lb()');chk(f'[{name}] local top-10 saved',len(lb)>=1 and lb[0]['i']=='BMW',str(lb[:2]))
    lab=await m.text_content('#shareBtn');chk(f'[{name}] share button label','I GAVE MOREHOUSE' in lab and 'MORE PROBLEMS' in lab,lab)
    await m.evaluate('navigator.share=undefined')
    if touch: await m.tap('#shareBtn')
    else: await m.click('#shareBtn')
    await m.wait_for_timeout(400)
    ls=await m.evaluate('__NW.lastShare');chk(f'[{name}] share works (copy fallback)','I gave Morehouse' in ls and 'more problems' in ls and 'notorious-weasel' in ls,ls)
    await m.wait_for_timeout(2400)
    if shots: await m.screenshot(path=OUT+'screenshot-end.png')
    chk(f'[{name}] ending theme',await m.evaluate('__NW.audio.theme')=='ending')
    if touch: await m.tap('#againBtn')
    else: await m.click('#againBtn')
    await m.wait_for_function('__NW.state==="play"',timeout=5000);chk(f'[{name}] play again',True)
    # natural play 14s
    await m.wait_for_timeout(14000)
    s=await m.evaluate('({p:__NW.problems,st:__NW.state,l:__NW.lives,t:__NW.trackI,f:__NW.frames})')
    chk(f'[{name}] natural play: auto-fire drops problems',s['p']>=3,str(s))
    chk(f'[{name}] no console errors/warnings',not errs,str(errs[:5]))
    await ctx.close()
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch(executable_path='/usr/bin/google-chrome',args=['--autoplay-policy=no-user-gesture-required'])
        dev=dict(p.devices['iPhone 13']);dev.pop('default_browser_type',None)
        await run(p,b,'iphone13',dev,True,True)
        if not LIVE:
            d2=dict(p.devices['iPhone SE']);d2.pop('default_browser_type',None)
            await run(p,b,'iphoneSE',d2,True,False)
            await run(p,b,'desktop',{'viewport':{'width':1280,'height':800}},False,False)
        await b.close()
    print('ALL PASS' if ok else 'SOME FAIL')
asyncio.run(main())
